modLoader="boxlin"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/ocpu/Boxlin/issues"
license="MIT"

[[mods]]
modId="boxlin"
displayName="Boxlin"
version="${file.jarVersion}"
logoFile="boxlin.png"
description="A language provider for Minecraft Forge. This provider will load Kotlin based mods."

